### ISSUE TITLE
Merge upstream

### ISSUE THREAD

**Issue by Frenzie** [koreader/sdcv#4]
I've got upstream ready over at https://github.com/Frenzie/sdcv/tree/v0.5.0_beta4

List of our commits that seem relevant:

<del>https://github.com/koreader/sdcv/commit/58ef78c5922585c695f019675eef58cbba12be9d add git ignore file</del> (edit: actually, this one doesn't seem relevant now that I've actually looked at it)
https://github.com/koreader/sdcv/commit/4c68c30013be9fb22dad978c78eb938553f91277 add cJSON library
https://github.com/koreader/sdcv/commit/17071c7b31dd5a92f03a8d118c4f944f4c170cf8 add json-output option
<del>https://github.com/koreader/sdcv/commit/b952af1c32d0ae209415418bb0d2e65b2217ab0b Add support for the &apos; entity</del> (already in upstream)
<del>https://github.com/koreader/sdcv/commit/3f77095dceaf9fdaa033390a0caaf891a0b4d2d9 add support for XML formated dictionary data</del> (already in upstream)
https://github.com/koreader/sdcv/commit/9ee1c9ec96c43968e77eec3b0a27064b6520f006 add suppport for HTML and Wikimedia dictionary data
https://github.com/koreader/sdcv/commit/53fe8151f5c4eee1ae9c12d579a52e1514e2410a print save to cache message to stderr so that it won't mess up JSON data
https://github.com/koreader/sdcv/commit/0d3852a42133e45b8842ca9e8343f4f51aa8beec get rid of 'Nothing similar to' message when there is no dict

@chrox Do you think I'm missing anything or that there's anything superfluous?

The final step would be to replace master. I was thinking of maybe renaming it to something else and making my v0.5.0_beta4 the new master after the merge?

A related issue is how to contribute our changes back to upstream. Something like `git format-patch COMMIT` sounds like it should be about right to generate patches to submit upstream.

**Comment by houqp** [comment]
> The final step would be to replace master. I was thinking of maybe renaming it to something else and making my v0.5.0_beta4 the new master after the merge?

Is v0.5.0_beta4 a pure mirror of upstream right now? I noticed it contains only the fork commit from @chrox , so i am a little bit confused.

> A related issue is how to contribute our changes back to upstream. Something like git format-patch COMMIT sounds like it should be about right to generate patches to submit upstream.

Yes, this should be the right approach.

**Comment by Frenzie** [comment]
From my quick tests rebasing didn't seem to want to work with pure upstream, but [merging proper 0.4.2 into @chrox' initial commit](https://github.com/Frenzie/sdcv/commit/13261aed1024dda71ec666ca2123e098f0861b99) was no issue (since they're identical). Plus I think that's preferable anyway for having the history available. From that point onward you can do pretty much whatever you want. Specifically, I want to `git rebase -i --onto` to pick which of our commits to apply to upstream while resolving the conflicts that will invariably arise. Pretty much anything else would be much more complex as far as I can tell (i.e., more conflicts) and be less conducive to contributing back upstream.

**Comment by houqp** [comment]
So if I understand it correctly, the new master will just be all the history in svn + our own commits? Ideally, renaming master branch should be avoided once it becomes public. In this case, renaming is probably fine because it's only used by us :)

**Comment by Frenzie** [comment]
Here's a sample upstream with our patches on top, for now mostly for the purpose of getting this stuff into upstream but in the hopefully nearby future in order to become our new default.

https://github.com/Frenzie/sdcv/commits/v0.5.4_beta4_koreader_changes

It compiles and seems to work okay.

**Comment by houqp** [comment]
Looks good to me. How about the one committed by chrox (23eda3e0272764d86ec2f9d8579d50625d668319)? Is it going to stay only in our fork?

**Comment by Frenzie** [comment]
You mean you want it gone from the history?

On May 7, 2016 12:56 AM, "Qingping Hou" <notifications@github.com> wrote:
>
> Looks good to me. How about the one committed by chrox (23eda3e
<https://github.com/koreader/sdcv/commit/23eda3e0272764d86ec2f9d8579d50625d668319>)?
Is it going to stay only in our fork?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
<https://github.com/koreader/sdcv/issues/4#issuecomment-217582909>

**Comment by chrox** [comment]
Sorry that I missed the discussions here. It doesn't matter if we include the first huge commit or not. Even rewriting the whole commit history should be OK, because each repo of this project has only one releasing branch. We don't need to maintain multiple snapshots for different platforms, which will make life much easier. So cherry-picking the real patches on top of the upstream 0.5.0_beta should be fine.

**Comment by Frenzie** [comment]
No problem. Could you take a look at https://github.com/Frenzie/sdcv/commits/v0.5.4_beta4_koreader_changes to see if I missed anything pertinent? Those are the patches I've already submitted upstream over at https://sourceforge.net/p/sdcv/patches/16/

Most important, I don't know if 7f21045094191804149b36a7cea3045bba0770d9 is automagically fixed by the upstream change to CMake or if it might need to be reapplied somehow.

**Comment by chrox** [comment]
The patches look good to me.  https://github.com/koreader/sdcv/commit/7f21045094191804149b36a7cea3045bba0770d9 is vital to build sdcv on Android and I will test on your branch and see if it's already capable to build on Android. Thanks for your work.

**Comment by Frenzie** [comment]
Done. Upstream integrated all of our patches.
